name: 持续集成

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Java环境
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        
    - name: 缓存Maven依赖
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: 编译项目
      run: mvn clean compile
      
    - name: 运行测试
      run: mvn test
      
    - name: 打包项目
      run: mvn package -DskipTests
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: myAuthAnalyzer-jar
        path: target/*.jar
        retention-days: 30 